-- Run this once in Supabase SQL Editor.
-- Public visitors can read and add approved comments,
-- and toggle their own anonymous reaction row.

create table if not exists public.game_reactions (
  id bigint generated by default as identity primary key,
  game_id text not null,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  constraint game_reactions_unique_visitor unique (game_id, visitor_id),
  constraint game_reactions_visitor_id_format check (visitor_id ~ '^[a-zA-Z0-9-]{16,80}$')
);

create table if not exists public.game_comments (
  id bigint generated by default as identity primary key,
  game_id text not null,
  name text not null,
  body text not null,
  status text not null default 'approved',
  created_at timestamptz not null default now(),
  constraint game_comments_name_length check (char_length(name) between 1 and 60),
  constraint game_comments_body_length check (char_length(body) between 1 and 800),
  constraint game_comments_status check (status in ('pending', 'approved', 'rejected'))
);

alter table public.game_reactions enable row level security;
alter table public.game_comments enable row level security;
alter table public.game_comments alter column status set default 'approved';

drop policy if exists "Anyone can read reactions" on public.game_reactions;
create policy "Anyone can read reactions"
  on public.game_reactions for select
  to anon, authenticated
  using (true);

drop policy if exists "Visitors can add reactions" on public.game_reactions;
create policy "Visitors can add reactions"
  on public.game_reactions for insert
  to anon, authenticated
  with check (visitor_id ~ '^[a-zA-Z0-9-]{16,80}$');

drop policy if exists "Visitors can remove reactions" on public.game_reactions;
create policy "Visitors can remove reactions"
  on public.game_reactions for delete
  to anon, authenticated
  using (visitor_id ~ '^[a-zA-Z0-9-]{16,80}$');

drop policy if exists "Anyone can read approved comments" on public.game_comments;
create policy "Anyone can read approved comments"
  on public.game_comments for select
  to anon, authenticated
  using (status = 'approved');

drop policy if exists "Visitors can submit pending comments" on public.game_comments;
drop policy if exists "Visitors can submit approved comments" on public.game_comments;
create policy "Visitors can submit approved comments"
  on public.game_comments for insert
  to anon, authenticated
  with check (status = 'approved');

grant select, insert, delete on public.game_reactions to anon, authenticated;
grant select, insert on public.game_comments to anon, authenticated;
grant usage, select on sequence public.game_reactions_id_seq to anon, authenticated;
grant usage, select on sequence public.game_comments_id_seq to anon, authenticated;
